// Auto-generated from country color files
// Generated on: 2025-11-21T22:50:45.258Z
// Source: country colors/
//
// Total countries: 168
// Colors from files: 118
// Fallback colors: 50

/**
 * Defines the basic data structure for a country
 */
export interface CountryData {
    name: string;
    color: string;
}

/**
 * Master map of all countries in the game (HOI4 tags)
 * Key: 3-letter HOI4 country tag (e.g., "USA", "PRC", "ENG")
 * Value: CountryData with display name and map color
 */
export const countryData = new Map<string, CountryData>([
    ["AFG", { name: "Afghanistan", color: "#40a0a7" }],
    ["ALB", { name: "Albania", color: "#952d66" }],
    ["ALG", { name: "Algeria", color: "#9163b4" }],
    ["ANG", { name: "Angola", color: "#71fa32" }],
    ["ARG", { name: "Argentina", color: "#919dec" }],
    ["ARM", { name: "Armenia", color: "#891f71" }],
    ["AST", { name: "Australia", color: "#398f61" }],
    ["AUS", { name: "Austria", color: "#e0e4ff" }],
    ["AZR", { name: "Azerbaijan", color: "#7c9450" }],
    ["BAH", { name: "BAH", color: "#b61618" }],
    ["BAN", { name: "Bangladesh", color: "#0000f3" }],
    ["BAS", { name: "BAS", color: "#71a22a" }],
    ["BEL", { name: "Belgium", color: "#c1ab08" }],
    ["BHU", { name: "Bhutan", color: "#9882bf" }],
    ["BLR", { name: "Belarus", color: "#74500a" }],
    ["BLZ", { name: "BLZ", color: "#97be19" }],
    ["BOL", { name: "Bolivia", color: "#ffb488" }],
    ["BOS", { name: "Bosnia", color: "#c3ff70" }],
    ["BOT", { name: "Botswana", color: "#b76232" }],
    ["BRA", { name: "Brazil", color: "#4c913f" }],
    ["BRD", { name: "BRD", color: "#2a65ac" }],
    ["BRM", { name: "Burma", color: "#00c800" }],
    ["BUL", { name: "Bulgaria", color: "#427145" }],
    ["CAM", { name: "Cambodia", color: "#6caa0a" }],
    ["CAN", { name: "Canada", color: "#773027" }],
    ["CAR", { name: "CAR", color: "#2e49b2" }],
    ["CBV", { name: "CBV", color: "#7bb828" }],
    ["CHA", { name: "Chad", color: "#62358a" }],
    ["CHI", { name: "China", color: "#fff4be" }],
    ["CHL", { name: "Chile", color: "#9b656b" }],
    ["CMR", { name: "Cameroon", color: "#8c3a26" }],
    ["COG", { name: "COG", color: "#be2d2f" }],
    ["COL", { name: "Colombia", color: "#debb5b" }],
    ["COM", { name: "COM", color: "#26c572" }],
    ["COS", { name: "Costa Rica", color: "#1eccb2" }],
    ["CRO", { name: "Croatia", color: "#f54646" }],
    ["CUB", { name: "Cuba", color: "#55c32c" }],
    ["CYP", { name: "CYP", color: "#17d920" }],
    ["CZE", { name: "Czech Republic", color: "#aabefa" }],
    ["DAH", { name: "DAH", color: "#62dc18" }],
    ["DEN", { name: "Denmark", color: "#99745d" }],
    ["DJI", { name: "DJI", color: "#c84332" }],
    ["DOM", { name: "Dominican Republic", color: "#ff000d" }],
    ["ECU", { name: "Ecuador", color: "#f99262" }],
    ["EGY", { name: "Egypt", color: "#e6e646" }],
    ["ELS", { name: "El Salvador", color: "#8730df" }],
    ["ENG", { name: "United Kingdom", color: "#c9385d" }],
    ["EQG", { name: "EQG", color: "#56d73c" }],
    ["ERI", { name: "Eritrea", color: "#1c8f8a" }],
    ["EST", { name: "Estonia", color: "#4c9dc3" }],
    ["ETH", { name: "Ethiopia", color: "#dc5e38" }],
    ["FIJ", { name: "FIJ", color: "#c8d449" }],
    ["FIN", { name: "Finland", color: "#cdd4e4" }],
    ["FRA", { name: "France", color: "#5071f0" }],
    ["GAB", { name: "Gabon", color: "#1e320a" }],
    ["GAM", { name: "GAM", color: "#d35a8b" }],
    ["GEO", { name: "Georgia", color: "#c16b3d" }],
    ["GER", { name: "Germany", color: "#4c6179" }],
    ["GHA", { name: "Ghana", color: "#0b55da" }],
    ["GNA", { name: "GNA", color: "#923526" }],
    ["GNB", { name: "GNB", color: "#932555" }],
    ["GRE", { name: "Greece", color: "#5db5e3" }],
    ["GUA", { name: "Guatemala", color: "#9d3020" }],
    ["GYA", { name: "GYA", color: "#a01c28" }],
    ["HAI", { name: "Haiti", color: "#962c4b" }],
    ["HOL", { name: "HOL", color: "#af391d" }],
    ["HON", { name: "Honduras", color: "#1b73b1" }],
    ["HUN", { name: "Hungary", color: "#f97e62" }],
    ["ICE", { name: "Iceland", color: "#647daf" }],
    ["IND", { name: "IND", color: "#b43e27" }],
    ["INS", { name: "Indonesia", color: "#e6aaa0" }],
    ["IRE", { name: "Ireland", color: "#509f5a" }],
    ["IRQ", { name: "Iraq", color: "#b27263" }],
    ["ISR", { name: "Israel", color: "#5477a8" }],
    ["ITA", { name: "Italy", color: "#437f3f" }],
    ["IVO", { name: "IVO", color: "#84cd13" }],
    ["JAM", { name: "JAM", color: "#8cb92d" }],
    ["JAP", { name: "Japan", color: "#ffbfbf" }],
    ["JOR", { name: "Jordan", color: "#efefb6" }],
    ["KAZ", { name: "Kazakhstan", color: "#1709f3" }],
    ["KEN", { name: "Kenya", color: "#948f4e" }],
    ["KOR", { name: "KOR", color: "#e71dc2" }],
    ["KOS", { name: "Kosovo", color: "#3974d3" }],
    ["KUW", { name: "Kuwait", color: "#fb612a" }],
    ["KYR", { name: "KYR", color: "#3acfbc" }],
    ["LAO", { name: "Laos", color: "#44aa5a" }],
    ["LAT", { name: "Latvia", color: "#705a57" }],
    ["LBA", { name: "LBA", color: "#e9d325" }],
    ["LEB", { name: "Lebanon", color: "#82963c" }],
    ["LIB", { name: "Libya", color: "#c8b45a" }],
    ["LIT", { name: "Lithuania", color: "#dbdb77" }],
    ["LUX", { name: "Luxembourg", color: "#41afb3" }],
    ["MAC", { name: "Macedonia", color: "#f9e06d" }],
    ["MAD", { name: "Madagascar", color: "#f06e5a" }],
    ["MAL", { name: "Malaysia", color: "#a8aa00" }],
    ["MEX", { name: "Mexico", color: "#689853" }],
    ["MLD", { name: "MLD", color: "#664ddb" }],
    ["MLI", { name: "Mali", color: "#9a78b3" }],
    ["MLT", { name: "MLT", color: "#3cec40" }],
    ["MLW", { name: "MLW", color: "#59cf76" }],
    ["MNT", { name: "Montenegro", color: "#fa515a" }],
    ["MOL", { name: "Moldova", color: "#f0ff70" }],
    ["MON", { name: "Mongolia", color: "#a1be66" }],
    ["MOR", { name: "Morocco", color: "#4bb7e4" }],
    ["MRT", { name: "MRT", color: "#9e5ad3" }],
    ["MZB", { name: "MZB", color: "#14339f" }],
    ["NEP", { name: "Nepal", color: "#c40020" }],
    ["NGA", { name: "NGA", color: "#267892" }],
    ["NGR", { name: "NGR", color: "#4d16a2" }],
    ["NIC", { name: "Nicaragua", color: "#224a96" }],
    ["NKR", { name: "North Korea", color: "#28015a" }],
    ["NMB", { name: "NMB", color: "#209d35" }],
    ["NOR", { name: "Norway", color: "#6f4747" }],
    ["NZL", { name: "New Zealand", color: "#9e292b" }],
    ["OMA", { name: "Oman", color: "#a6bfa7" }],
    ["PAK", { name: "Pakistan", color: "#1777f3" }],
    ["PAN", { name: "Panama", color: "#3823b8" }],
    ["PAR", { name: "Paraguay", color: "#3971e4" }],
    ["PER", { name: "Peru", color: "#c4bdcc" }],
    ["PHI", { name: "Philippines", color: "#22bfa0" }],
    ["PNG", { name: "PNG", color: "#c81e94" }],
    ["POL", { name: "Poland", color: "#c55c6a" }],
    ["POR", { name: "Portugal", color: "#277446" }],
    ["PRC", { name: "PRC", color: "#55c81e" }],
    ["PRU", { name: "PRU", color: "#9f2cba" }],
    ["QAT", { name: "Qatar", color: "#71684c" }],
    ["RAJ", { name: "British Raj", color: "#aa0a0a" }],
    ["RCG", { name: "RCG", color: "#d3d131" }],
    ["ROM", { name: "Romania", color: "#ebd85c" }],
    ["RUS", { name: "Russia", color: "#7d0d18" }],
    ["RWA", { name: "RWA", color: "#28e6dd" }],
    ["SAF", { name: "South Africa", color: "#5740d4" }],
    ["SAU", { name: "Saudi Arabia", color: "#abbe98" }],
    ["SEN", { name: "Senegal", color: "#36beb3" }],
    ["SIA", { name: "Siam", color: "#41d8b4" }],
    ["SIE", { name: "SIE", color: "#3cddc0" }],
    ["SLO", { name: "Slovakia", color: "#36a79c" }],
    ["SLV", { name: "Slovenia", color: "#68d6ff" }],
    ["SOL", { name: "SOL", color: "#32a1ec" }],
    ["SOM", { name: "Somalia", color: "#3a5d76" }],
    ["SPR", { name: "Spain", color: "#f2cd5e" }],
    ["SRB", { name: "Serbia", color: "#5a506e" }],
    ["SRL", { name: "SRL", color: "#50cea9" }],
    ["STP", { name: "STP", color: "#d04dd5" }],
    ["SUD", { name: "Sudan", color: "#ee998a" }],
    ["SWE", { name: "Sweden", color: "#2484f7" }],
    ["SWI", { name: "Switzerland", color: "#210e13" }],
    ["SYR", { name: "Syria", color: "#646496" }],
    ["TAJ", { name: "TAJ", color: "#9bdd4b" }],
    ["TMS", { name: "TMS", color: "#cf59d4" }],
    ["TOG", { name: "TOG", color: "#a02313" }],
    ["TRI", { name: "TRI", color: "#47a40e" }],
    ["TUN", { name: "Tunisia", color: "#a9197b" }],
    ["TUR", { name: "Turkey", color: "#941e45" }],
    ["TZN", { name: "TZN", color: "#25991e" }],
    ["UAE", { name: "United Arab Emirates", color: "#d28371" }],
    ["UGA", { name: "Uganda", color: "#302b116" }],
    ["UKR", { name: "Ukraine", color: "#005ab9" }],
    ["URG", { name: "URG", color: "#b61811" }],
    ["USA", { name: "USA", color: "#437bed" }],
    ["UZB", { name: "Uzbekistan", color: "#2b838f" }],
    ["VEN", { name: "Venezuela", color: "#ce1126" }],
    ["VIN", { name: "VIN", color: "#beae13" }],
    ["VOL", { name: "VOL", color: "#a7372f" }],
    ["WES", { name: "WES", color: "#2dd312" }],
    ["YEM", { name: "Yemen", color: "#d623e7" }],
    ["ZAM", { name: "Zambia", color: "#5326fa" }],
    ["ZIM", { name: "Zimbabwe", color: "#00d25a" }]
]);
