// Auto-generated country data from modern state files
// Generated on: 2025-11-21T21:48:52.778Z
// Source: modern states/
//
// Total countries: 152

/**
 * Defines the basic data structure for a country
 */
export interface CountryData {
    name: string;
    color: string;
}

/**
 * Master map of all countries in the game (HOI4 tags)
 * Key: 3-letter HOI4 country tag (e.g., "USA", "PRC", "ENG")
 * Value: CountryData with display name and map color
 */
export const countryData = new Map<string, CountryData>([
    ["AFG", { name: "Afghanistan", color: "#a32929" }],
    ["ALB", { name: "Albania", color: "#2557d0" }],
    ["ALG", { name: "Algeria", color: "#9ee935" }],
    ["ANG", { name: "Angola", color: "#da6ccd" }],
    ["ARG", { name: "Argentina", color: "#86ead9" }],
    ["ARM", { name: "Armenia", color: "#b86d14" }],
    ["AST", { name: "Australia", color: "#5631c4" }],
    ["AUS", { name: "Austria", color: "#47dd40" }],
    ["AZR", { name: "Azerbaijan", color: "#ed5a8b" }],
    ["BAN", { name: "Bangladesh", color: "#8dc2e2" }],
    ["BEL", { name: "Belgium", color: "#a2ad1f" }],
    ["BHU", { name: "Bhutan", color: "#b318dc" }],
    ["BLR", { name: "Belarus", color: "#4bd28f" }],
    ["BOL", { name: "Bolivia", color: "#e37d63" }],
    ["BOS", { name: "Bosnia and Herzegovina", color: "#7e88f1" }],
    ["BOT", { name: "BOT", color: "#57a329" }],
    ["BRA", { name: "Brazil", color: "#d02597" }],
    ["BRD", { name: "BRD", color: "#35e1e9" }],
    ["BRM", { name: "Myanmar", color: "#dabe6c" }],
    ["BUL", { name: "Bulgaria", color: "#b386ea" }],
    ["CAM", { name: "Cambodia", color: "#14b82f" }],
    ["CAN", { name: "Canada", color: "#c43144" }],
    ["CAR", { name: "CAR", color: "#4082dd" }],
    ["CBV", { name: "CBV", color: "#c2ed5a" }],
    ["CHA", { name: "Chad", color: "#e28de2" }],
    ["CHI", { name: "China", color: "#1fad83" }],
    ["CHL", { name: "Chile", color: "#dc6918" }],
    ["CMR", { name: "Cameroon", color: "#5c4bd2" }],
    ["COL", { name: "Colombia", color: "#79e363" }],
    ["COS", { name: "Costa Rica", color: "#f17eb3" }],
    ["CRO", { name: "Croatia", color: "#2985a3" }],
    ["CUB", { name: "Cuba", color: "#d0c825" }],
    ["CYP", { name: "CYP", color: "#ac35e9" }],
    ["CZE", { name: "Czech Republic", color: "#6cda95" }],
    ["DAH", { name: "DAH", color: "#ea8e86" }],
    ["DEN", { name: "Denmark", color: "#1437b8" }],
    ["DOM", { name: "Dominican Republic", color: "#7bc431" }],
    ["ECU", { name: "Ecuador", color: "#dd40bd" }],
    ["EGY", { name: "Egypt", color: "#5aede0" }],
    ["ELS", { name: "El Salvador", color: "#e2c28d" }],
    ["ENG", { name: "United Kingdom", color: "#4d1fad" }],
    ["EQG", { name: "EQG", color: "#18dc20" }],
    ["ERI", { name: "ERI", color: "#d24b6e" }],
    ["EST", { name: "Estonia", color: "#63a9e3" }],
    ["ETH", { name: "Ethiopia", color: "#def17e" }],
    ["FIN", { name: "Finland", color: "#9329a3" }],
    ["FRA", { name: "France", color: "#25d088" }],
    ["GAB", { name: "Gabon", color: "#e96835" }],
    ["GAM", { name: "GAM", color: "#6c6dda" }],
    ["GEO", { name: "Georgia", color: "#a3ea86" }],
    ["GER", { name: "Germany", color: "#b81475" }],
    ["GHA", { name: "Ghana", color: "#31b2c4" }],
    ["GNA", { name: "GNA", color: "#ddc240" }],
    ["GNB", { name: "GNB", color: "#a85aed" }],
    ["GRE", { name: "Greece", color: "#8de2a2" }],
    ["GUA", { name: "Guatemala", color: "#ad1f26" }],
    ["HAI", { name: "Haiti", color: "#185bdc" }],
    ["HOL", { name: "HOL", color: "#a1d24b" }],
    ["HON", { name: "Honduras", color: "#e363da" }],
    ["HUN", { name: "Hungary", color: "#7ef1d8" }],
    ["ICE", { name: "Iceland", color: "#a36529" }],
    ["INS", { name: "Indonesia", color: "#4725d0" }],
    ["IRE", { name: "Ireland", color: "#45e935" }],
    ["IRQ", { name: "Iraq", color: "#da6c96" }],
    ["ISR", { name: "Israel", color: "#86c9ea" }],
    ["ITA", { name: "Italy", color: "#b2b814" }],
    ["IVO", { name: "IVO", color: "#9e31c4" }],
    ["JAP", { name: "Japan", color: "#40dd87" }],
    ["JOR", { name: "Jordan", color: "#ed715a" }],
    ["KAZ", { name: "Kazakhstan", color: "#8d98e2" }],
    ["KEN", { name: "Kenya", color: "#5bad1f" }],
    ["KOR", { name: "KOR", color: "#dc18a5" }],
    ["KOS", { name: "Kosovo", color: "#4bd2d1" }],
    ["KUW", { name: "Kuwait", color: "#e3bd63" }],
    ["KYR", { name: "KYR", color: "#ad7ef1" }],
    ["LAO", { name: "Laos", color: "#29a337" }],
    ["LAT", { name: "Latvia", color: "#d02543" }],
    ["LBA", { name: "LBA", color: "#3589e9" }],
    ["LEB", { name: "Lebanon", color: "#c0da6c" }],
    ["LIB", { name: "Libya", color: "#e486ea" }],
    ["LIT", { name: "Lithuania", color: "#14b880" }],
    ["LUX", { name: "Luxembourg", color: "#c46731" }],
    ["MAC", { name: "Macedonia", color: "#4c40dd" }],
    ["MAD", { name: "Madagascar", color: "#7aed5a" }],
    ["MAL", { name: "Malaysia", color: "#e28db9" }],
    ["MEX", { name: "Mexico", color: "#1f91ad" }],
    ["MLI", { name: "Mali", color: "#dcca18" }],
    ["MLW", { name: "MLW", color: "#9e4bd2" }],
    ["MNT", { name: "Montenegro", color: "#63e38c" }],
    ["MOL", { name: "Moldova", color: "#f1827e" }],
    ["MON", { name: "Mongolia", color: "#2949a3" }],
    ["MOR", { name: "Morocco", color: "#84d025" }],
    ["MRT", { name: "MRT", color: "#e935cd" }],
    ["MZB", { name: "MZB", color: "#6cdacb" }],
    ["NEP", { name: "Nepal", color: "#eabf86" }],
    ["NGA", { name: "NGA", color: "#4214b8" }],
    ["NGR", { name: "NGR", color: "#33c431" }],
    ["NIC", { name: "Nicaragua", color: "#dd4070" }],
    ["NKR", { name: "North Korea", color: "#5ab1ed" }],
    ["NMB", { name: "NMB", color: "#d9e28d" }],
    ["NOR", { name: "Norway", color: "#941fad" }],
    ["NZL", { name: "New Zealand", color: "#18dc80" }],
    ["OMA", { name: "Oman", color: "#d26b4b" }],
    ["PAK", { name: "Pakistan", color: "#636ae3" }],
    ["PAN", { name: "Panama", color: "#a6f17e" }],
    ["PAR", { name: "Paraguay", color: "#a32977" }],
    ["PER", { name: "Peru", color: "#25c4d0" }],
    ["PHI", { name: "Philippines", color: "#e9c135" }],
    ["PNG", { name: "PNG", color: "#a26cda" }],
    ["POL", { name: "Poland", color: "#86ea99" }],
    ["POR", { name: "Portugal", color: "#b81424" }],
    ["PRC", { name: "People's Republic of China", color: "#316ac4" }],
    ["PRU", { name: "PRU", color: "#abdd40" }],
    ["RAJ", { name: "British India", color: "#ed5ae9" }],
    ["RCG", { name: "RCG", color: "#8de2cc" }],
    ["ROM", { name: "Romania", color: "#ad5e1f" }],
    ["RUS", { name: "Russia", color: "#3618dc" }],
    ["RWA", { name: "RWA", color: "#5ed24b" }],
    ["SAF", { name: "South Africa", color: "#e3639a" }],
    ["SAU", { name: "Saudi Arabia", color: "#7ed1f1" }],
    ["SEN", { name: "Senegal", color: "#a3a129" }],
    ["SIA", { name: "SIA", color: "#9b25d0" }],
    ["SIE", { name: "SIE", color: "#35e97d" }],
    ["SLO", { name: "Slovakia", color: "#da786c" }],
    ["SLV", { name: "Slovenia", color: "#8698ea" }],
    ["SOL", { name: "SOL", color: "#62b814" }],
    ["SOM", { name: "Somalia", color: "#c431a2" }],
    ["SPR", { name: "Spain", color: "#40ddd4" }],
    ["SRB", { name: "Serbia", color: "#edb95a" }],
    ["SUD", { name: "Sudan", color: "#ab8de2" }],
    ["SWE", { name: "Sweden", color: "#1fad28" }],
    ["SWI", { name: "Switzerland", color: "#dc1845" }],
    ["SYR", { name: "Syria", color: "#4b91d2" }],
    ["TAJ", { name: "TAJ", color: "#cbe363" }],
    ["TMS", { name: "TMS", color: "#e57ef1" }],
    ["TOG", { name: "TOG", color: "#29a373" }],
    ["TUN", { name: "Tunisia", color: "#d05b25" }],
    ["TUR", { name: "Turkey", color: "#3935e9" }],
    ["TZN", { name: "TZN", color: "#8ada6c" }],
    ["UAE", { name: "United Arab Emirates", color: "#ea86be" }],
    ["UGA", { name: "Uganda", color: "#149fb8" }],
    ["UKR", { name: "Ukraine", color: "#c4af31" }],
    ["URG", { name: "URG", color: "#9940dd" }],
    ["USA", { name: "United States", color: "#5aed82" }],
    ["UZB", { name: "Uzbekistan", color: "#e28d8e" }],
    ["VEN", { name: "Venezuela", color: "#1f4bad" }],
    ["VIN", { name: "VIN", color: "#8edc18" }],
    ["VOL", { name: "VOL", color: "#d24bc4" }],
    ["WES", { name: "WES", color: "#63e3cc" }],
    ["YEM", { name: "Yemen", color: "#f1ba7e" }],
    ["ZAM", { name: "Zambia", color: "#4529a3" }],
    ["ZIM", { name: "Zimbabwe", color: "#2fd025" }]
]);
